### ISSUE TITLE
Comma-separated selectors to style multiple elements

### ISSUE THREAD

**Issue by cyouh95** [maltloaf/f1-3-c2p1-colmar-academy#2]
You could use comma-separated selectors to specify shared properties for multiple elements. This can help you simplify your code and reduce the number of lines you have.

```css
.content h6, .content p  { 
   padding-left: 0.9rem; 
 } 
```

https://github.com/maltloaf/f1-3-c2p1-colmar-academy/blob/3fa6a6cb652e98932ee0178ef69abe6445a102a7/ColmarAcademy/resources/css/stylemobile.css#L85-L91
